apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-sample-api.fullname" . }}
  labels:
    {{- include "node-sample-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http # port name on the deployment: http
      protocol: TCP
      name: http
  selector:
    {{- include "node-sample-api.selectorLabels" . | nindent 4 }}
