apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-sample-api.fullname" . }}
  labels:
    {{- include "node-sample-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http # port name on the deployment: http
      protocol: TCP
      name: http
    ## Additional for metrics
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics # port name on the deployment: metrics
      protocol: TCP
      name: metrics
    ## Additional for metrics
  selector:
    {{- include "node-sample-api.selectorLabels" . | nindent 4 }}
